export const INCREASE_ITEM = 'INCREASE_ITEM';
export const ADD_ORDER_NUMBER = 'ADD_ORDER_NUMBER';
export const DELETE_ITEM = 'DELETE_ITEM';
export const INCREASE_PRODUCT_ITEM = 'INCREASE_PRODUCT_ITEM';
export const INSTALL_DATA = 'INSTALL_DATA';
export const CHANGE_ITEM = 'CHANGE_ITEM';
